export type ScaffoldFile = { path: string; content: string }

function toSnakeCase(name: string): string {
  return name.replace(/-/g, '_')
}

export function generateFiles(projectName: string, features: string[]): ScaffoldFile[] {
  const snake = toSnakeCase(projectName)
  const files: ScaffoldFile[] = []

  // 1. README.md
  files.push({
    path: 'README.md',
    content: `# ${projectName}

A Solana dApp built with Next.js 14 + Anchor.
Generated by [SolScaffold](https://solscaffold.vercel.app)

## Quick Start
\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Stack
- Next.js 14 App Router
- Anchor 0.31
- Tailwind CSS + shadcn/ui
- Wallet Adapter (Phantom, Solflare, Backpack)
`,
  })

  // 2. .gitignore
  files.push({
    path: '.gitignore',
    content: `node_modules
.next
target
.anchor
test-ledger
.env.local
.DS_Store
*.tsbuildinfo
dist
`,
  })

  // 3. .env.example
  files.push({
    path: '.env.example',
    content: `NEXT_PUBLIC_RPC_URL=https://api.devnet.solana.com
NEXT_PUBLIC_NETWORK=devnet
`,
  })

  // 4. package.json (root workspace)
  const rootPkg = {
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'pnpm --filter app dev',
      build: 'pnpm --filter app build',
      'anchor:build': 'anchor build',
      'anchor:test': 'anchor test',
    },
    devDependencies: {
      '@coral-xyz/anchor': '^0.31.1',
      typescript: '^5.6.3',
    },
  }
  files.push({ path: 'package.json', content: JSON.stringify(rootPkg, null, 2) + '\n' })

  // 5. pnpm-workspace.yaml
  files.push({
    path: 'pnpm-workspace.yaml',
    content: `packages:
  - 'app'
`,
  })

  // 6. Anchor.toml
  files.push({
    path: 'Anchor.toml',
    content: `[features]
resolution = true
skip-lint = false

[programs.localnet]
${projectName} = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test"
`,
  })

  // 7. Cargo.toml (workspace)
  files.push({
    path: 'Cargo.toml',
    content: `[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
`,
  })

  // 8. app/package.json
  const appDeps: Record<string, string> = {
    next: '^14.2.18',
    react: '^18.3.1',
    'react-dom': '^18.3.1',
    '@coral-xyz/anchor': '^0.31.1',
    '@solana/web3.js': '^1.98.0',
    '@solana/wallet-adapter-base': '^0.9.23',
    '@solana/wallet-adapter-react': '^0.15.35',
    '@solana/wallet-adapter-react-ui': '^0.9.35',
    '@solana/wallet-adapter-wallets': '^0.19.32',
    'class-variance-authority': '^0.7.1',
    clsx: '^2.1.1',
    'lucide-react': '^0.460.0',
    'tailwind-merge': '^2.5.4',
    'tailwindcss-animate': '^1.0.7',
  }
  if (features.includes('sns')) {
    appDeps['@bonfida/spl-name-service'] = '^3.0.7'
  }
  if (features.includes('usdc') || features.includes('token2022')) {
    appDeps['@solana/spl-token'] = '^0.4.9'
  }
  if (features.includes('nft')) {
    appDeps['@metaplex-foundation/mpl-token-metadata'] = '^3.4.0'
    appDeps['@metaplex-foundation/umi'] = '^0.9.2'
    appDeps['@metaplex-foundation/umi-bundle-defaults'] = '^0.9.2'
  }
  if (features.includes('magicblock')) {
    appDeps['@magicblock-labs/ephemeral-rollups-sdk'] = '^0.2.5'
  }

  const appPkg = {
    name: 'app',
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: appDeps,
    devDependencies: {
      '@types/node': '^22.9.0',
      '@types/react': '^18.3.12',
      '@types/react-dom': '^18.3.1',
      autoprefixer: '^10.4.20',
      postcss: '^8.4.49',
      tailwindcss: '^3.4.14',
      typescript: '^5.6.3',
    },
  }
  files.push({ path: 'app/package.json', content: JSON.stringify(appPkg, null, 2) + '\n' })

  // 9. app/tsconfig.json
  const tsconfig = {
    compilerOptions: {
      target: 'es2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }
  files.push({ path: 'app/tsconfig.json', content: JSON.stringify(tsconfig, null, 2) + '\n' })

  // 10. app/next.config.mjs
  files.push({
    path: 'app/next.config.mjs',
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {}
export default nextConfig
`,
  })

  // 11. app/tailwind.config.ts
  files.push({
    path: 'app/tailwind.config.ts',
    content: `import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('tailwindcss-animate')],
}

export default config
`,
  })

  // 12. app/postcss.config.mjs
  files.push({
    path: 'app/postcss.config.mjs',
    content: `export default { plugins: { tailwindcss: {}, autoprefixer: {} } }
`,
  })

  // 13. app/app/globals.css
  files.push({
    path: 'app/app/globals.css',
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
  })

  // 14. app/app/layout.tsx
  files.push({
    path: 'app/app/layout.tsx',
    content: `import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers'
import { WalletButton } from '../components/WalletButton'

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'A Solana dApp built with Next.js 14 + Anchor',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <header className="flex items-center justify-between p-4 border-b">
            <span className="font-bold">${projectName}</span>
            <WalletButton />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
`,
  })

  // 15. app/app/providers.tsx
  files.push({
    path: 'app/app/providers.tsx',
    content: `"use client"

import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react'
import { WalletModalProvider } from '@solana/wallet-adapter-react-ui'
import { PhantomWalletAdapter, SolflareWalletAdapter } from '@solana/wallet-adapter-wallets'
import { useMemo } from 'react'
import '@solana/wallet-adapter-react-ui/styles.css'

export function Providers({ children }: { children: React.ReactNode }) {
  const endpoint = process.env.NEXT_PUBLIC_RPC_URL ?? 'https://api.devnet.solana.com'
  const wallets = useMemo(
    () => [new PhantomWalletAdapter(), new SolflareWalletAdapter()],
    []
  )

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect>
        <WalletModalProvider>
          {children}
        </WalletModalProvider>
      </WalletProvider>
    </ConnectionProvider>
  )
}
`,
  })

  // 16. app/app/page.tsx
  files.push({
    path: 'app/app/page.tsx',
    content: `import { WalletButton } from '../components/WalletButton'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold mb-4">${projectName}</h1>
      <p className="text-muted-foreground mb-8">Built on Solana</p>
      <WalletButton />
    </main>
  )
}
`,
  })

  // 17. app/components/WalletButton.tsx
  files.push({
    path: 'app/components/WalletButton.tsx',
    content: `"use client"

import { WalletMultiButton } from '@solana/wallet-adapter-react-ui'

export function WalletButton() {
  return <WalletMultiButton />
}
`,
  })

  // 18. app/lib/solana.ts
  files.push({
    path: 'app/lib/solana.ts',
    content: `import { Connection, clusterApiUrl } from '@solana/web3.js'

export const NETWORK = (process.env.NEXT_PUBLIC_NETWORK ?? 'devnet') as
  | 'mainnet-beta'
  | 'devnet'
  | 'testnet'

export const connection = new Connection(
  process.env.NEXT_PUBLIC_RPC_URL ?? clusterApiUrl('devnet'),
  'confirmed'
)
`,
  })

  // Conditional files
  if (features.includes('sns')) {
    files.push({
      path: 'app/lib/sns.ts',
      content: `import { Connection, PublicKey } from '@solana/web3.js'
import { resolve } from '@bonfida/spl-name-service'

// SNS only works on mainnet — hardcode mainnet RPC for resolution
const MAINNET_RPC = 'https://api.mainnet-beta.solana.com'
const mainnetConnection = new Connection(MAINNET_RPC, 'confirmed')

export async function resolveSolDomain(domain: string): Promise<PublicKey | null> {
  const normalized = domain.trim().toLowerCase().replace(/\\.sol$/, '')
  if (!normalized) return null
  try {
    return await resolve(mainnetConnection, normalized)
  } catch {
    return null
  }
}
`,
    })
  }

  if (features.includes('usdc')) {
    files.push({
      path: 'app/lib/usdc.ts',
      content: `import { PublicKey } from '@solana/web3.js'

export const USDC_MINT_MAINNET = new PublicKey(
  'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
)
export const USDC_MINT_DEVNET = new PublicKey(
  '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU'
)

// sendUsdc is provided in lib/solana/send.ts — import from there
`,
    })
  }

  if (features.includes('nft')) {
    files.push({
      path: 'app/lib/nft.ts',
      content: `// NFT minting with Metaplex UMI
// Setup: create a UMI instance with umi-bundle-defaults, then pass it here.
// See: https://developers.metaplex.com/token-metadata

export async function mintNft(_params: {
  name: string
  uri: string
  sellerFeeBasisPoints: number
}): Promise<string> {
  // TODO: implement with @metaplex-foundation/mpl-token-metadata
  // import { createNft } from '@metaplex-foundation/mpl-token-metadata'
  // const { signature } = await createNft(umi, { ... }).sendAndConfirm(umi)
  throw new Error('mintNft: UMI instance required — wire it up in your component')
}
`,
    })
  }

  // 19. programs/{projectName}/Cargo.toml
  files.push({
    path: `programs/${projectName}/Cargo.toml`,
    content: `[package]
name = "${projectName}"
version = "0.1.0"
description = "Created with SolScaffold"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "${snake}"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.31.1"
`,
  })

  // 20. programs/{projectName}/src/lib.rs
  files.push({
    path: `programs/${projectName}/src/lib.rs`,
    content: `use anchor_lang::prelude::*;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[program]
pub mod ${snake} {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
        msg!("Greetings from: {:?}", ctx.program_id);
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
`,
  })

  return files
}
